spring.application.name=iam-client
server.port=8080

spring.security.oauth2.client.registration.iam-client.client-id=iam-client
spring.security.oauth2.client.registration.iam-client.client-secret=iam-secret
spring.security.oauth2.client.registration.iam-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.iam-client.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/iam-client
spring.security.oauth2.client.registration.iam-client.scope=openid,profile

spring.security.oauth2.client.provider.iam-client.issuer-uri=http://localhost:9000